### ISSUE TITLE
Feedback per E-Mail erhalten: HTTPS, Favicon, Sozial Media Meta-Tags und mehr

### ISSUE THREAD

**Issue by mritzmann** [dnszensur/corruption2.com#3]
![feedback_permail](https://user-images.githubusercontent.com/4533780/30603058-b78071a0-9d66-11e7-8f3b-8b00efcc4030.png)

**Comment by mritzmann** [comment]
Technisch:

- [ ] Favicon
- [ ] HTTP Status Code 451
- [ ] Open Graph und Twitter tags
- [ ] Anzeige genutzer DNS
- [ ] Gültiges TLS Zertifikat

Text:

- [ ] Grund dafür
- [ ] Vorzeige- und Test-Domain
- [ ] welcher nicht von deinem Anbieter (kleines D, weil kein Brief!?)
